---
title: An R Markdown document converted from "2022-01-11_FCD_clinical_data_set_bindary_data_summary.ipynb"
output: html_document
---

```{r}
library(heatmap3)
library(reshape2)
```

```{r}
df <- read.csv("./clinical_association/2022-02-07_clinical_data_set.csv",header = TRUE, sep =",", stringsAsFactors=T)
```

```{r}
df
```

```{r}
colnames(df)
df.colname<-colnames(df)
```

```{r}
indexofVariableOfInterest<-NA
VariableOfInterest<-df.colname[c(3:16)]
for (i in 1:length(VariableOfInterest)){
    indexofVariableOfInterest[i]<-which(colnames(df)==VariableOfInterest[i])
}
indexofVariableOfInterest
```

```{r}
# Make helper function to map metadata category to color
mapDrugToColor<-function(annotations){
    colorsVector = ifelse(annotations[VariableOfInterest]==0, 
        "grey90", "#FF2E2E")
    return(colorsVector)
    }
```

```{r}
df.annotation<-df[,indexofVariableOfInterest]
df[,indexofVariableOfInterest]
```

```{r}
colannotation<-mapDrugToColor(df.annotation)
rownames(colannotation)<-df[,1]
```

```{r}
colannotation<-as.matrix(colannotation)
colannotation
```

```{r}
colannotation2<-t(colannotation)
colannotation2
```

```{r}
takes <- df.colname[c(19:25,27,30)]
takes
```

```{r}
df.binarydata <- df[ , (names(df) %in% takes)]
rownames(df.binarydata)<-df[,1]
```

```{r}
df.binarydata<-as.matrix(df.binarydata)
df.binarydata
```

```{r}
df.melt<-melt(df.binarydata)
```

```{r}
df.melt$value[is.na(df.melt$value)]<- -1
df.melt
```

```{r}
df.binarydata_NA_converted<-dcast(df.melt,Var1 ~ Var2)
```

```{r}
df.binarydata_NA_converted
```

```{r}
rownames(df.binarydata_NA_converted)<-df.binarydata_NA_converted$Var1
```

```{r}
df.binarydata_NA_converted2<-df.binarydata_NA_converted[,!((names(df.binarydata_NA_converted) %in% c("Var1")))]
```

```{r}
df.binarydata_NA_converted3<-t(df.binarydata_NA_converted2)
df.binarydata_NA_converted3
```

```{r}
# Test heatmap with column annotations
testHeatmap<-function(df0.trans, df0.annotation) {    
    sampleColors = mapDrugToColor(colannotation)
    heatmap(df0.trans, margins=c(10,10), col = c("grey", "forestgreen"), ColSideColors=sampleColors)
    }
```

```{r}
df.binarydata_NA_converted3
```

```{r}
colannotation2
```

```{r}
par(mar = c(1, 1, 1, 1))
```

```{r}
pdf("./clinical_association/2022-02-07_clinical_binary_data_summary.pdf")
heatmap3(t(df.binarydata_NA_converted3), scale="none" , RowSideColors=t(colannotation2), showRowDendro=FALSE,
         Rowv=NA, Colv=NA, col=c("grey","grey90", "#50C878"), showColDendro=FALSE)
dev.off()
```

